services:
  # O BANCO DE DADOS NÃO ESTÁ MAIS AQUI! Nós o criamos manualmente.

  # Serviço 1: O Backend
  - type: web
    name: taskflow-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        postgresql://postgres1:rSjxUGOoqvk0W8lj3dbzbXZ6SDejw87s@dpg-d1al10adbo4c73cjr8r0-a/to_do_list_ywod
        value: "COLE_AQUI_A_INTERNAL_CONNECTION_STRING_DO_PASSO_2"
      - key: JWT_SECRET
        sync: false 
      - key: PORT
        value: 10000 

  # Serviço 2: O Frontend
  - type: web
    name: taskflow-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: taskflow-backend
          property: url