# render.yaml - Versão atualizada para usar seus Dockerfiles
services:
  # 1. Banco de Dados PostgreSQL (Substitui o serviço 'db' do docker-compose)
  - type: pserv
    name: taskflow-db
    env: postgres
    plan: free 
    postgresMajorVersion: 14

  # 2. Serviço de Backend (Usa seu backend/Dockerfile)
  - type: web
    name: taskflow-backend
    env: docker
    plan: free
    # Caminho para o seu Dockerfile de backend
    dockerfilePath: ./backend/Dockerfile
    # IMPORTANTE: Este é o comando do seu docker-compose.yml
    startCommand: "sh -c 'npx prisma migrate deploy && npm start'"
    # Disco persistente para uploads
    disks:
      - name: uploads-disk
        mountPath: /app/uploads # O WORKDIR no seu Dockerfile é /app
        sizeGB: 1
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: taskflow-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # Render gera um segredo seguro
      - key: PORT
        value: 4000

  # 3. Serviço de Frontend (Usa seu frontend/Dockerfile)
  - type: web
    name: taskflow-frontend
    env: docker
    plan: free
    # Caminho para o seu Dockerfile de frontend
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: taskflow-backend
          property: url
          