services:
  # Serviço 1: O Banco de Dados PostgreSQL
  - type: db  # CORREÇÃO: O tipo correto para um banco de dados gerenciado é 'db'
    name: taskflow-db
    plan: free 
    databaseName: to_do_list
    postgres:
      version: 14 # Define a versão do PostgreSQL
    
  # Serviço 2: O Backend em Node.js/Express
  - type: web
    name: taskflow-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromService:
          type: db # CORREÇÃO: O tipo do serviço de origem agora é 'db'
          name: taskflow-db
          property: connectionString
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        sync: false

  # Serviço 3: O Frontend em Next.js
  - type: web
    name: taskflow-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: taskflow-backend
          property: url