# render.yaml - Teste: Apenas o Frontend
services:
  - type: web
    name: taskflow-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://backend-nao-existe.com" # Usando um valor temporário e inválido
