services:
  # Serviço 1: O Banco de Dados PostgreSQL
  - type: postgres # CORREÇÃO DEFINITIVA: O tipo para bancos de dados PostgreSQL é simplesmente 'postgres'
    name: taskflow-db
    plan: free 
    postgres:
      version: 14

  # Serviço 2: O Backend em Node.js/Express
  - type: web
    name: taskflow-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres # CORREÇÃO: A referência agora é para o serviço do tipo 'postgres'
          name: taskflow-db
          property: connectionString
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        sync: false # Lembre-se de configurar este segredo no painel do Render

  # Serviço 3: O Frontend em Next.js
  - type: web
    name: taskflow-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: taskflow-backend
          property: url