services:
  # Serviço 1: O Banco de Dados PostgreSQL
  - type: pserv 
    name: taskflow-db
    env: postgres 
    plan: free 
    
  # Serviço 2: O Backend em Node.js/Express
  - type: web
    name: taskflow-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv 
          name: taskflow-db
          property: connectionString
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        sync: false

  # Serviço 3: O Frontend em Next.js
  - type: web
    name: taskflow-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: taskflow-backend
          property: url