services:
  # 1. Banco de Dados PostgreSQL (com a palavra-chave 'runtime' correta)
  - type: pserv
    name: taskflow-db
    runtime: postgres # <-- A CORREÇÃO ESTÁ AQUI!
    plan: free

  # 2. Serviço de Backend (com a seção 'disks' de volta)
  - type: web
    name: taskflow-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    disks:
      - name: uploads-disk
        mountPath: /app/uploads
        sizeGB: 1
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: taskflow-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 4000

  # 3. Serviço de Frontend
  - type: web
    name: taskflow-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: taskflow-backend
          property: url
